# Generated by Django 3.2.13 on 2022-04-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgalleery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGalleery',
            new_name='ProductGallery',
        ),
    ]
